# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
    branches:
        include: [ main ]
    paths:
        include: [ "scripts/**.ps1" ]

pool:
  vmImage: windows-latest

steps:
- powershell: |
    .\tests\Install-Pester.ps1
  name: Modules
  displayName: 'Install modules'
  workingDirectory: $(build.sourcesDirectory)
  errorActionPreference: continue

- powershell: |
    Import-Module -Name "PSScriptAnalyzer" -Force -ErrorAction "Stop"
    $Results = Invoke-ScriptAnalyzer -Path "$(build.sourcesDirectory)\scripts" -Recurse -ReportSummary
    $Results | Select-Object -Property RuleName, Severity, ScriptName, Line | Format-Table -AutoSize
    $Results | ConvertTo-Csv | Out-File -Path "$(build.sourcesDirectory)\PSScriptAnalyzer.csv" -Encoding utf8
  name: PSScriptAnalyzer
  displayName: 'Test with PSScriptAnalyzer'
  workingDirectory: $(build.sourcesDirectory)
  errorActionPreference: continue

- publish: "$(build.sourcesDirectory)\\PSScriptAnalyzer.csv"
  artifact: PSScriptAnalyzerResults
  name: 'Publish PSScriptAnalyzer test artifacts'

- powershell: |
    Import-Module -Name "Pester" -Force -ErrorAction "Stop"
    $Config = New-PesterConfiguration
    $Config.Run.Path = "$(build.sourcesDirectory)\tests"
    $Config.Run.PassThru = $True
    $Config.TestResult.Enabled = $True
    $Config.TestResult.OutputFormat = "NUnitXml"
    $Config.TestResult.OutputPath = "$(build.sourcesDirectory)\TestResults.xml"
    $Config.Output.Verbosity = "Detailed"
    Invoke-Pester -Configuration $Config
  name: Pester
  displayName: 'Test with Pester'
  workingDirectory: $(build.sourcesDirectory)
  errorActionPreference: continue

- publish: "$(build.sourcesDirectory)\\TestResults.xml"
  artifact: PesterTestResults
  name: 'Publish Pester test artifacts'

- task: PublishTestResults@2
  name: 'Publish PSScriptAnalyzer results'
  inputs:
    testResultsFormat: "NUnit"
    testResultsFiles: "$(build.sourcesDirectory)\\TestResults.xml"
    failTaskOnFailedTests: true
    testRunTitle: "Publish Pester results"
